## Part A - Vectorized Programming with NumPy
### Task 1 - Arrays, Statistics, and Indexing

In [1]:
import numpy as np

# Set random seed for reproducibility
np.random.seed(42)

In [14]:
# Generate Array A with 100 random integers
array_a = np.random.randint(0, 101, 100)
print("A:",array_a)

# Calculate statistics
a_min = np.min(array_a)
a_max = np.max(array_a)
a_median = np.median(array_a)
a_mean = np.mean(array_a)
a_std = np.std(array_a)

print("Array A Statistics:")
print("Min:",a_min,"and","Max:",a_max)
print("Median:",a_median,"\nMean:",a_mean,"\nStd Dev:",a_std.round(2))

A: [ 44  12  91  57  19  91  71  60  38   0   2  76  91  61  62  24  55  32
  37   5  57  43  44  31  44  60  46  20  79  84  74 100  35  98  18  19
  56  17  46  48  13  14  30   0  53   2  15  86  56  74  11  73  95  15
  71  75  23  27   7  91  35  89   7  57  59  49  27  91 100  40  99  63
  26  62  16  72  32  83  76  91  28  12  45  34   5  81  68  46  24  65
   9  55  29   4  32  64  17  95  48  10]
Array A Statistics:
Min: 0 and Max: 100
Median: 46.0 
Mean: 47.23 
Std Dev: 28.99


In [17]:
# Generate Array B with exactly 100 values
array_b = np.arange(101)
print("Array B:",array_b)
print("Number of elements",len(array_b))

Array B: [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100]
Number of elements 101


In [20]:
# Implement np.zeros() and np.ones()
zeros_arr = np.zeros((3, 4))
ones_arr = np.ones((2, 2))

print("Zeros Array:\n",zeros_arr)
print(f"Shape: {zeros_arr.shape}, Data Type: {zeros_arr.dtype}\n")

print("Ones Array:\n",ones_arr)
print(f"Shape: {ones_arr.shape}, Data Type: {ones_arr.dtype}\n")

Zeros Array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Shape: (3, 4), Data Type: float64

Ones Array:
 [[1. 1.]
 [1. 1.]]
Shape: (2, 2), Data Type: float64



In [23]:
# Create an array of 5 evenly spaced values between 0 and 10
linspace_arr = np.linspace(0, 10, 5)
print(f"Linspace Array: {linspace_arr}\n")

Linspace Array: [ 0.   2.5  5.   7.5 10. ]



In [24]:
# Create a 2D Array (Matrix)
array_2d = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120]
])

# Create a 3D Array (Tensor)
array_3d = np.array([
    [[1, 2], [3, 4]], 
    [[5, 6], [7, 8]]
])

print("--- 2D Array Properties ---")
print(f"Shape: {array_2d.shape}") # (Rows, Columns)
print(f"Dimensions (ndim): {array_2d.ndim}")
print(f"Indexing (Row 1, Col 2): {array_2d[1, 2]}") # Outputs 70
print(f"Slicing (First two rows, columns 1 to 2):\n{array_2d[0:2, 1:3]}\n")

print("--- 3D Array Properties ---")
print(f"Shape: {array_3d.shape}") # (Depth, Rows, Columns)
print(f"Dimensions (ndim): {array_3d.ndim}")
print(f"Indexing (Depth 1, Row 0, Col 1): {array_3d[1, 0, 1]}") # Outputs 6
print(f"Slicing (First block, all rows, first column):\n{array_3d[0, :, 0]}\n")

--- 2D Array Properties ---
Shape: (3, 4)
Dimensions (ndim): 2
Indexing (Row 1, Col 2): 70
Slicing (First two rows, columns 1 to 2):
[[20 30]
 [60 70]]

--- 3D Array Properties ---
Shape: (2, 2, 2)
Dimensions (ndim): 3
Indexing (Depth 1, Row 0, Col 1): 6
Slicing (First block, all rows, first column):
[1 3]



In [7]:
# Create a 1D array of 12 items, then reshape it into a 3x4 matrix
original_1d = np.arange(12)
reshaped_matrix = original_1d.reshape((3, 4))

print("Reshaped Matrix (2D):")
print(reshaped_matrix)

# Flatten it back to 1D
flattened_array = reshaped_matrix.flatten()

print("\nFlattened Array (1D):")
print(flattened_array)

Reshaped Matrix (2D):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Flattened Array (1D):
[ 0  1  2  3  4  5  6  7  8  9 10 11]
