In [2]:
import numpy as np

# Create two 2x2 matrices
matrix_x = np.array([
    [1, 2],
    [3, 4]
])

matrix_y = np.array([
    [5, 6],
    [7, 8]
])

# Addition
matrix_add = matrix_x + matrix_y

# Element-wise multiplication
matrix_elementwise = matrix_x * matrix_y

# Matrix multiplication using the @ operator (equivalent to np.matmul)
matrix_mult = matrix_x @ matrix_y

print("--- Matrix Arithmetic ---")
print("Matrix X + Matrix Y:\n", matrix_add)
print("\nElement-wise Multiplication (X * Y):\n", matrix_elementwise)
print("\nMatrix Multiplication (X @ Y):\n", matrix_mult, "\n")

--- Matrix Arithmetic ---
Matrix X + Matrix Y:
 [[ 6  8]
 [10 12]]

Element-wise Multiplication (X * Y):
 [[ 5 12]
 [21 32]]

Matrix Multiplication (X @ Y):
 [[19 22]
 [43 50]] 



In [3]:
# Define a square matrix
A = np.array([
    [4, 7],
    [2, 6]
])

print("--- Linear Algebra ---")
print("Original Matrix A:\n", A)

# 1. Find the transpose
A_transpose = A.T
print("\nTranspose of A:\n", A_transpose)

# 2. Find the determinant
# We use np.linalg.det for determinants
A_det = np.linalg.det(A)
print(f"\nDeterminant of A: {A_det:.2f}")

# 3. Check for invertibility, find inverse, and verify
# A matrix is invertible if its determinant is not zero
if A_det != 0:
    # Find the inverse
    A_inverse = np.linalg.inv(A)
    print("\nInverse of A (A^-1):\n", A_inverse)
    
    # Verify A @ A^-1 equals the Identity matrix
    # np.eye(2) generates a 2x2 Identity matrix
    # np.allclose() safely compares floating-point numbers
    is_identity = np.allclose(A @ A_inverse, np.eye(A.shape[0]))
    
    print("\nVerification (A @ A^-1 == Identity Matrix):")
    print(is_identity)
else:
    print("\nMatrix A is singular (determinant is 0) and cannot be inverted.")

--- Linear Algebra ---
Original Matrix A:
 [[4 7]
 [2 6]]

Transpose of A:
 [[4 2]
 [7 6]]

Determinant of A: 10.00

Inverse of A (A^-1):
 [[ 0.6 -0.7]
 [-0.2  0.4]]

Verification (A @ A^-1 == Identity Matrix):
True
